### PR TITLE
Add Erlang installation from package

### PR DESCRIPTION
**Pull request by robertkowalski**
It takes less time than compiling from source every run

### CODE REVIEW

**Comment by otakup0pe** [comment]
Definitely agree that the package option would be great. Instead of downloading the deb directly, can you use the `apt_repository` module?

**Comment by robertkowalski** [comment]
hi @otakup0pe I updated the PR - sorry for the delay, was quite busy

**Comment by soupdiver** [comment]
Just two things from looking over quickly:
1. Don't you need `sudo: yes` also for installing the package?
2. I would prefer the multi line syntax instead of the single line one.

**Comment by robertkowalski** [comment]
thank you for your suggestions! fixed

**Comment by soupdiver** [comment]
:+1:

**Comment by robertkowalski** [comment]
@soupdiver I noticed several problems when using apt instead of downloading the package.

The apt-repo is just supporting the three latest versions:

```
vagrant@vagrant-ubuntu-trusty-64:~$ apt-cache policy erlang
erlang:
  Installed: (none)
  Candidate: 1:17.4
  Version table:
     1:17.4 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
     1:17.3.2 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
     1:17.3 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
     1:17.1 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
     1:16.b.3-dfsg-1ubuntu2.1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
     1:16.b.3-dfsg-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

Installing the latest version works, but if i try to install another version i get:

```
The following packages have unmet dependencies:
 erlang : Depends: erlang-diameter but it is not going to be installed
          Depends: erlang-eldap but it is not going to be installed
          Recommends: erlang-ic-java but it is not going to be installed
          Recommends: erlang-src but it is not going to be installed
          Recommends: erlang-examples but it is not going to be installed

msg: 'apt-get install 'erlang=1:17.3.2'' failed: E: Unable to correct problems, you have held broken packages.
```

**Comment by soupdiver** [comment]
Looks like a dependency problem and that only the latest version is properly supported.
So maybe a note would be useful that specific versions are not available when installing via repository
@otakup0pe Do you have any thought about that?

**Comment by otakup0pe** [comment]
Definitely add a note about specific versions not being supported with package mode. Otherwise I'll check out the PR today.

**Comment by robertkowalski** [comment]
Or we could switch back to download the deb from the website which worked without problems afaik

**Comment by otakup0pe** [comment]
My preference is to use apt as-is but update the README. If you need an older version you can go by source. This kind of problem is relatively common...

**Comment by soupdiver** [comment]
Would it make sense to support `package`to get the version provided by Ubuntu and `otp_package` to download the latest version from the website?

**Comment by otakup0pe** [comment]
Sure. I think supporting both works much in the way we support deb / binary for nodejs.

**Pull request closed without merging**
